# Generated by Django 4.2.5 on 2023-11-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_time',
            new_name='totime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='fromtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='laptop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.laptop'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
