# Generated by Django 4.2.5 on 2023-11-27 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_rename_reservation_time_reservation_totime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='laptop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.laptop'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
